# Task 4: Bingo Web app

Bingo is a game where players are given a 5x5 grid of numbers ranging from 1 to 75. Each square in the grid should hold a number such that each number is repeated not more than once. Numbers are drawn at random from a pool of numbers from 1 to 75. The game is won when a player obtains 5 in a row horizontally, vertically or diagonally.

![image](Student Created Tasks/Resource Files/Bingo/bingo_grid.png)

---

## Task 1.1

Create a program that creates a 5x5 grid of numbers and store it in a file called `BINGO.txt` with each line being each row of the grid.

Your program should:
- Create a 5x5 grid of random numbers between 1 to 75.
- Each number should be unique and appear only once per grid.
- The center square (3rd row, 3rd column) should be a string `Free`.
- store the grid in a file called `BINGO.txt`.

Test your program by reading the file `BINGO.txt` and outputing the contents. Each line should printed separately.

---

## Task 1.2

You are given a file `TEST.txt`. `TEST.txt` is a 2D grid that contains numbers from 1 to 75. Each number is unqiue with the center being the string "Free".

Write a Python function `bingo(grid)` that generates a random number between 1 and 75 inclusive when the user inputs the string "Next". When the user inputs the string "End", the program will check through a 5x5 grid of numbers. If a number in the grid was generated by the program, replace that number with the boolean `True`. Otherwise, replace it with the boolean `False`.

The function should:
- Generate a random number in the range 1 to 75 and store it each time the user inputs the string "Next". Each number should only appear once.
- Return an appropriate message if all the numbers have already been generated.
- Checks through a 5x5 grid of numbers and replaces the numbers with Booleans when the user inputs the string "End". `True` if the number has been generated and `False` if the number has not been generated.
- Return the new 5x5 grid of Booleans.

Test your program on the 5x5 grid in `TEST.txt` and print the result.

---

## Task 1.3

Write a Python function `grid_check(grid)` that checks if all the elements in a line in the 2D grid are `True`.

The function should:
- Check if all the elements in a line are `True`. Your program should check horizontally, vertically and diagonally.
- return `True` if the above requirement is met. Otherwise, return `False`.

Test your function using 2 5x5 grids and returning the results.

---

## Task 1.4

Create a Web app called Bingo Game. The home page of the Web app should first ask the user for the number of players, then redirect to a new page where there is a red button with white text "Generate number" on it. There should also be a button to end the game at the bottom of the page.
The Web app should:
- Ask the user for the number of players and create an equal number of bingo cards.
- Each time the user presses the red button, generate a random number between 1 and 75. The numbers should not repeat.
- When the user presses the end button, ask the user which player has called bingo, check if the bingo is valid and return an appropriate result on the screen.
- If all 75 number have appeared, print the string "Tie, no winners.".
- After the game has ended a button to redirect the user back to the home page should appear.

The bingo cards should always be shown on the screen with the appropriate player numbers above them. The cards should be displayed below the number generator
---
